spring:
  datasource:
    url: jdbc:mysql://192.168.56.10:3306/test?characterEncoding=utf8
    username: root
    password: root

  jpa:
    show-sql: true
    database: MYSQL
    hibernate:
      ddl-auto: update
  jooq:
    sql-dialect: